# Generated by Django 3.1.2 on 2020-10-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.CharField(max_length=255)),
                ('is_item', models.BooleanField()),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.category', verbose_name='Category ')),
            ],
        ),
    ]
