# Generated by Django 3.1.2 on 2020-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costam', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_img_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='item_short_desc',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_item',
            field=models.BooleanField(default=True),
        ),
    ]
