# Generated by Django 3.1.2 on 2020-10-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_auto_20201011_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_img_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_short_desc',
            field=models.CharField(max_length=120),
        ),
    ]
