# Generated by Django 3.1.2 on 2020-10-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_contactdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsFromUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('user_email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
